
# cargo-vet audits file

[[audits.regex]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.11.2 -> 1.11.3"
notes = "It just increments the minimum version of regex-automata."

[[audits.regex]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "1.11.3 -> 1.12.2"

[[audits.regex-automata]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.4.9 -> 0.4.11"
notes = "It's a combination of format!() syntax tweaks and added calls to .shrink_to_fit()."

[[audits.regex-automata]]
who = "Oliver Hamlet <git@ortham.net>"
criteria = "safe-to-deploy"
delta = "0.4.11 -> 0.4.13"

[[trusted.esplugin]]
criteria = "safe-to-deploy"
trusted-publisher = "github:Ortham/esplugin"
start = "2025-09-29"
end = "2027-01-19"
notes = "This is my own crate, published from my own Git repo using Trusted Publishing."

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 55123 # rust-lang-owner
start = "2024-08-15"
end = "2026-09-16"
notes = "rust-lang-owner is a bot run by the Rust Infrastructure Team, so libc is hopefully as trustworthy as the Rust toolchain."

[[trusted.windows-link]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2026-09-17"
notes = "kennykerr is on the Windows team at Microsoft."

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2026-09-17"
notes = "kennykerr is on the Windows team at Microsoft."

[[trusted.windows-targets]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-09"
end = "2026-09-17"
notes = "kennykerr is on the Windows team at Microsoft."
